#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

   _  
  / /_    __    / /(_)_ __  _   ___  __
 / /\ \  / /   / / | | '_ \| | | \ \/ /
/ /__\ \/ /   / /__| | | | | |_| |>  < 
\____/ /\ \   \____/_|_| |_|\__,_/_/\_\ 
    /_/  \_\

Welcome to LX Linux (a distribution for purists)


!
exec /bin/sh